name: Fetch latest outages

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '*/10 * * * *'

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Fetch
      run: |        
        curl -s 'https://ags.pge.esriemcs.com/arcgis/rest/services/43/outages/MapServer/5/query?where=1%3D1&outFields=*&f=pjson' \
          | jq '.features | map({
            attributes: (.attributes | del(.blueSkyNotificationSubscription, .OBJECTID)),
            geometry_x: .geometry.x,
            geometry_y: .geometry.y
          } | .attributes + {geometry_x: .geometry_x, geometry_y: .geometry_y})' \
          > outages.json
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
